use tauri::State;

use crate::db::AppState;
use crate::errors::AppError;
use crate::models::HistoryEntry;
use crate::services::HistoryService;

#[tauri::command]
pub fn list_history(state: State<'_, AppState>) -> Result<Vec<HistoryEntry>, AppError> {
    HistoryService::new(state.db.clone()).list_history()
}

#[tauri::command]
pub fn get_history_entry(id: String, state: State<'_, AppState>) -> Result<HistoryEntry, AppError> {
    HistoryService::new(state.db.clone()).get_entry(id)
}

#[tauri::command]
pub fn delete_history_entry(id: String, state: State<'_, AppState>) -> Result<(), AppError> {
    HistoryService::new(state.db.clone()).delete_entry(id)
}

#[tauri::command]
pub fn clear_history(state: State<'_, AppState>) -> Result<(), AppError> {
    HistoryService::new(state.db.clone()).clear_history()
}

/// Save a dictation result to history.
///
/// `id` and `timestamp` are generated by the service; `was_inserted` is always
/// `false` until Phase 9 text insertion is implemented.
#[tauri::command]
pub fn create_history_entry(
    raw_text: String,
    cleaned_text: String,
    mode_used: String,
    state: State<'_, AppState>,
) -> Result<HistoryEntry, AppError> {
    HistoryService::new(state.db.clone()).create_history_entry(HistoryEntry {
        id: String::new(),
        raw_text,
        cleaned_text,
        mode_used,
        timestamp: String::new(),
        was_inserted: false,
    })
}

#[cfg(test)]
mod tests {
    use std::sync::{Arc, Mutex};

    use crate::db::migrations::run_migrations;
    use crate::models::HistoryEntry;
    use crate::services::HistoryService;
    use rusqlite::Connection;

    fn setup() -> Arc<Mutex<Connection>> {
        let conn = Connection::open_in_memory().unwrap();
        run_migrations(&conn).unwrap();
        Arc::new(Mutex::new(conn))
    }

    fn blank_entry(raw: &str, cleaned: &str, mode: &str) -> HistoryEntry {
        HistoryEntry {
            id: String::new(),
            raw_text: raw.to_string(),
            cleaned_text: cleaned.to_string(),
            mode_used: mode.to_string(),
            timestamp: String::new(),
            was_inserted: false,
        }
    }

    #[test]
    fn test_create_generates_id_and_timestamp() {
        let svc = HistoryService::new(setup());
        let entry = svc
            .create_history_entry(blank_entry("hello", "Hello.", "smart"))
            .unwrap();
        assert!(!entry.id.is_empty(), "id must be generated");
        assert!(!entry.timestamp.is_empty(), "timestamp must be generated");
        assert_eq!(entry.raw_text, "hello");
        assert_eq!(entry.cleaned_text, "Hello.");
        assert_eq!(entry.mode_used, "smart");
        assert!(!entry.was_inserted, "was_inserted must be false");
    }

    #[test]
    fn test_create_entry_appears_in_list() {
        let svc = HistoryService::new(setup());
        svc.create_history_entry(blank_entry("raw a", "clean a", "email"))
            .unwrap();
        svc.create_history_entry(blank_entry("raw b", "clean b", "developer"))
            .unwrap();
        let list = svc.list_history().unwrap();
        assert_eq!(list.len(), 2);
    }

    #[test]
    fn test_create_raw_equals_cleaned_when_no_cleanup() {
        let svc = HistoryService::new(setup());
        let entry = svc
            .create_history_entry(blank_entry("dictated text", "dictated text", "raw"))
            .unwrap();
        assert_eq!(entry.raw_text, entry.cleaned_text);
    }

    #[test]
    fn test_created_entries_have_unique_ids() {
        let svc = HistoryService::new(setup());
        let a = svc
            .create_history_entry(blank_entry("a", "a", "smart"))
            .unwrap();
        let b = svc
            .create_history_entry(blank_entry("b", "b", "smart"))
            .unwrap();
        assert_ne!(a.id, b.id, "each entry must have a unique UUID");
    }
}
